### PR TITLE
Expose windows Count

### PR DESCRIPTION
**Pull request by giladlev23**
Hi!

I would like to propose exposing the _Count_ of the _curr_ and _prev_ windows inside _Limiter_.
On my usage, I have a map with values of type _Limiter_, and I would like to remove keys from the map according to whether the inner _Counter_ of a _limiter_ is empty (zero).

Would very much appreciate it, thanks in advance!

### CODE REVIEW

**Comment by RussellLuo** [comment]
> I would like to remove keys from the map according to whether the inner Counter of a limiter is empty (zero).

Hi, giladlev23!

Only the counter of an idle limiter, whose `Allow()` has never been called, will be zero. Are these idle limiters the target keys that you want to remove from your map?

**Comment by giladlev23** [comment]
Thanks for the quick response.

For your question - yes, some limiters can be idle in my case.
Additionally, I want to sort them by the counters to remove the smallest (due to memory issues), so either the counters are relevant for this case.

**Comment by giladlev23** [comment]
> Thanks for the quick response.
> 
> For your question - yes, some limiters can be idle in my case. Additionally, I want to sort them by the counters to remove the smallest (due to memory issues), so either the counters are relevant for this case.

a

**Comment by RussellLuo** [comment]
To control the total memory usage, people usually use a shared memory zone for a group of limiters. For example, Nginx's `ngx_http_limit_req_module` uses [a LRU zone](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_zone):

>  If the zone storage is exhausted, the least recently used state is removed.

I have implemented a `ratelimit` module for Caddy, which also uses [a LRU zone](https://github.com/RussellLuo/caddy-ext/blob/master/ratelimit/zone.go) (based on `slidingwindow`). If that satisfies your needs, maybe I should move the zone implementation to this repo.

As for the proposed solution, I think your map is also a shared memory zone. However, I'm afraid the count of a limiter is an internal state, which may not be very suitable for public access. In `slidingwindow`, the core API of a limiter is inspired by [golang.org/x/time/rate](https://pkg.go.dev/golang.org/x/time/rate), and I think it's better to keep it as minimal (and focused) as possible.

**Comment by giladlev23** [comment]
Hi! :)

Let me explain the needed solution better, and maybe you'll have something
to offer.

I am using a vertical method (limiter per IP/MAC) in addition to
a horizontal method (one limiter for the whole system) since
my use-case requires it.
I'm actually already using an LRU cache for my limiter as you suggested,
and I agree this is a good solution for the multiple limiters problem.
My LRU cache is pretty big, with thousands of entries, but my problem is
logging - I want to dump to a certain log the top X (let's say 100)
limiters, by counters, for debugging purposes, for example for adjusting
over time the rate-limit, since I can't know in advance the behavior of the
traffic.

The solution I came up with is getting the internal counter in order to
know which are the top X.
I think that even though it's an internal counter for internal
calculations, it can become public as a solution for my problem or other
similar ones.
Maybe even adding another counter with publication intention, but I just
wanted to be efficient and not to add any logic.

If you have any other ideas I would love to hear them!
Thank you!

**Comment by RussellLuo** [comment]
Hi giladlev23, thanks for your explanation!

> ... ,but my problem is
> logging - I want to dump to a certain log the top X (let's say 100)
> limiters, by counters, for debugging purposes, for example for adjusting
> over time the rate-limit, ...
> ...
> I think that even though it's an internal counter for internal
> calculations, it can become public as a solution for my problem or other
> similar ones.

I think the use case you described here is a very special one, which is not common enough for the purpose of rate-limiting itself. So I'm afraid this is not a typical case that `slidingwindow` should support currently. On the other hand, It's much easier to add an API than to remove one, so I'd prefer wait to expand the APIs until we're sure it addresses common use cases.

> Maybe even adding another counter with publication intention, but I just
> wanted to be efficient and not to add any logic.
>
> If you have any other ideas I would love to hear them!

The best solution that comes up to my mind right now is to make a fork of this repo, and change `slidingwindow.Limiter` to expose its inner windows' count to address your special problem.

**Comment by RussellLuo** [comment]
As for your original problem (i.e. to adjust the over time rate-limit), I think your solution of logging TOP-X limiters will work only if you want to decrease the limit value of a limiter, in case that the actual traffic is lower than the specified limit.

Because the maximum count of a single window is `Limiter.Limit()`, suppose you have a limiter Lim1 with the limit value (say 100), you will get the log as below if the traffic is higher than expected:

```
limiter: Lim1, prev-count: 100, curr-count: 100
```

Then, you will have no idea how to increase the limit value, since the rejected amount of traffic is unknown. The alternative solution may be to record the rejected count of the limiter, instead of their allowed count.

**Comment by giladlev23** [comment]
Hi,

You are right, I have metrics regarding the traffic above the limit rate
since I'm holding count on the traffic I reject from the system.

That is the exact reason I'm asking for the internal counter - to have
metrics/logs regarding what happens below the rate limit because without
the internal counter it's a black box for me.
I want to know how close are limiters below the rate limit to it, so I
adjust the limit to have more places for little picks and still block high
rate limiters.

**Comment by RussellLuo** [comment]
If you can already find a way to get the metrics about REJECTED COUNT, then it's recommended to **use the same mechanism** for recording metrics about TOTAL COUNT and ALLOWED COUNT. Once you get these three kinds of COUNTs, it's easy to calculate any difference values to help you make adjustment decisions.

**Comment by giladlev23** [comment]
The metrics I need (and have) for REJECTED DATA are as follows - Packets
received counter, for each IP/MAC (which as maintained each IP/MAC has its
own rate limiter).

The metric I want to add for the ALLOWED DATA is not a simple counter as
for REJECTED DATA, but the top X counters along time.
There are multiple reasons why I can't implement the same metric, one of
them is that there is a huge amount of ALLOWED data in comparison to
REJECTED data, so the number of metrics will be equivalent huge if I won't
use only the top X (which satisfies my needs).
The approach I used here is using a heap (similar to
https://pkg.go.dev/container/heap#example-package-IntHeap) to
constantly hold the top X, by the counter.
In order to implement the heap of top X, I'll need access to the internal
counter and re-order the heap constantly by it.

That's why I can't just use the same mechanism as you suggested for both
metrics since they are different by design and purpose.


And again, thank you for keeping replying and trying to help me find a solution to my problem.
I'm sure we'll find a solution, whether exposing the counter or something
else.

**Comment by RussellLuo** [comment]
> There are multiple reasons why I can't implement the same metric, one of
> them is that there is a huge amount of ALLOWED data in comparison to
> REJECTED data, so the number of metrics will be equivalent huge ...

If both REJECTED DATA and ALLOWED DATA are maintained for each IP/MAC, I think their cardinalities are equal (i.e. the total amount of different IP/MACs), although each ALLOWED counter value may be much greater than the corresponding REJECTED counter value. Unless the REJECTED DATA is a single counter for the whole system, or not for each IP/MAC?

**Comment by giladlev23** [comment]
I meant that the amount of IP/MACs that will exceed that rate limit is
lower than the amount of IP/MACs won't.
My usage of rate limiting is for dealing with traffic extreme picks (that
overload our pipeline), so unless a traffic pick arrives, all data is
considered ALLOWED DATA, so as said - it's a huge amount of data in
comparison to the REJECTED DATA, and I want to use metrics only for the top
X.

**Comment by RussellLuo** [comment]
Now I understand your problem better. Yes, I admit that the amount of different IP/MACs will be huge, as it always is ;)

Then I think I have two suggestions:
1. Adopt your TOP-X solution by using your own fork of `slidingwindow`, which exposes the window counts as you expected.
2. If you already have (or are willing to add) a ELK-like logging system, then the amount of IP/MACs is no longer huge, since typically every request can be logged. Just print ALLOWED/REJECTED logs for each limiter, and use ELK to gather metrics for you.

**Comment by giladlev23** [comment]
I'm using Prometheus for metrics collection and Datadog based on them.

I don't like the idea of forking from the package because I'll miss bug
fixes, features, and other changes in the main package branch.
In addition, I don't think adding the internal counter would be a bad
thing, and actually, I think more users will find it helpful and it'll
create opportunities for more flexible usage that some users wouldn't think
about without the Counter exposed.
I can't see why exposing it will be such a bad thing. I get that the
guideline is the less complex the better, but I really don't take the
Counter as internal and irrelevant for users.

**Comment by RussellLuo** [comment]
As a general design principle, the core behavior of an object is always defined by its API. I think the core behavior of a limiter is **to decide whether the given event is allowed or not**, so its core API is `Allow`. And the counts (as well as the Sliding Window Algorithm itself) are internal implementations used to help the limiter make the decision.

In your use case, the usage of limiter's count is primarily for gathering metrics, which I think should be addressed by other mechanisms (e.g. ELK) instead of a rate-limiting library like `slidingwindow`. However, if exposing the limiter's count is currently the easiest way to resolve your problem at hand, it's ok to do it.

That being said, I'll still be open to add the Count API if finally there are enough evidences (and real-world use cases) to justify it. But maybe "right now" is not the best time ;)

**Comment by giladlev23** [comment]
Let me try and explain the whole picture once more :)

I use slidingwindow as a rate-limiter and not as a metrics collector.

I use both vertical and horizontal rate-limiting -
*Horizontal *- the standard usage of rate-limiting, one limiter for the
whole system, that rejects packets above the rate limit.
That method is protecting the system from overflowing traffic, but the
packets that will be rejected will be random.
*Vertical *- In order to keep important entities (IP/MAC) from rejecting, I
hold a limiter per entity in addition.
If an entity exceeds the rate limit it will be blocked individually.
Those specific limiters are dynamically configurable and can be adjusted in
the case of an important entity that has a lot of traffic but is important
enough to get a higher rate limit for example.

The combination of both methods allows us to protect important entities and
also protect the whole system.
For example, if all entities reach 99% of their limit - none of the
specific limiters will reject data but the horizontal limiter will.


We have multiple customers whose default configuration should be different
from each other, based on their network traffic and other parameters.
That is why, in the matter of metrics, I need to have visibility of the
limiters status under and above the rate limit and above, to answer
questions like -
* How close is the "normal" traffic behavior to the limit? In order to
increase the limit and avoid small pick interruptions.
* How much above the limit has an entity reached? For analyzing the network
behavior.
* For how long has an entity crossed the limit? For analyzing the network
behavior.

To get to this data I'll need metrics, under and above the limit -
*Above the limit *- I use Prometheus to count each entity when I decide to
reject it (similar to your proposal).
That way I can get a graph over time with the rate behavior of entities
that cross that rate limit.
I can use this method, and collect data naively, because there are not
supposed to be more than a few above the limit.
*Under the limit *- I can't use the same method because there is a lot of
traffic under the rate limit and it will be a huge amount of metrics.
Instead, I use *heap *to constantly hold the top X entities, by the
internal Counter we are talking about, and dump them to metrics.
I don't need the data about entities that are not close to the rate limit,
especially when there are a lot of them.

The only difference between the metrics collection above and under the rate
limit is that I want and need to collect only some of the data and not
everything, and to do so I need a way to sort to get the top X.

I really understand the principle for API exposure that you mentioned, and
this is really a good question whether to expose it or not.
I don't see another way to handle my use case, and I genuinely see this
usage as a pretty common one and not so unique, which is worth the exposure.

I think the counter is indeed not a standard API call that indicates the
purpose of the package, but it is not so internal as well.
Maybe you'll prefer something like GetCurrentCount as it might be more
elegant than just Counter, because it's more like a method rather than an
element of the struct.
I forgot to mention, but I realized that the exposure of the "prev" counter
is unnecessary and is really too internal, and only the "curr" counter is
indicating the limiter state.

Thanks!

**Comment by RussellLuo** [comment]
Thanks for your detailed reply, and your persistence is impressive 👍

> Instead, I use *heap *to constantly hold the top X entities, by the
> internal Counter we are talking about, and dump them to metrics.

Are the metrics you mentioned here are also based on Prometheus, if it's so, then how can you keep a *heap*-like structure for Prometheus metrics? Or in other words, what are the metric types and labels you are using for the top X entities?

> I think the counter is indeed not a standard API call that indicates the
> purpose of the package

That is exactly the point I'm concerned. AFAIK, popular libraries for rate-limiting, such as [golang.org/x/time/rate](https://pkg.go.dev/golang.org/x/time/rate) and [uber-go/ratelimit](https://github.com/uber-go/ratelimit), do not expose the inner counts either. If this is a common use case, why don't they provide the *count*-like APIs?

**Comment by giladlev23** [comment]
> Are the metrics you mentioned here are also based on Prometheus, if it's so, then how can you keep a heap-like structure for Prometheus metrics? Or in other words, what are the metric types and labels you are using for the top X entities?
It's the same as the metrics for entities above the limit - each metric contains the entity itself, timestamp, etc. The over-time look of the metrics can teach about network behavior.

And again, I agree with the conflict in approach upon exposure, and I think it's debatable in this case.

Currently, I'm using reflection to access the internal counter, which is a pretty bad practice, with bad performance, and quite unsafe, and that's why I keep insisting on the right solution here :).

**Comment by RussellLuo** [comment]
> I forgot to mention, but I realized that the exposure of the "prev" counter
> is unnecessary and is really too internal, and only the "curr" counter is
> indicating the limiter state.

After some thought, I think there is an alternative solution for this case, that is exposing the current window by implementing a new limiter based on `slidingwindow.Limiter`. For example:

```go
package main

import (
	"fmt"
	"time"

	sw "github.com/RussellLuo/slidingwindow"
)

type Limiter struct {
	*sw.Limiter
	CurrWindow sw.Window
}

func NewLimiter(size time.Duration, limit int64, newWindow sw.NewWindow) (*Limiter, sw.StopFunc) {
	lim := new(Limiter)
	var stop sw.StopFunc

	lim.Limiter, stop = sw.NewLimiter(size, limit, func() (sw.Window, sw.StopFunc) {
		win, s := newWindow()
		lim.CurrWindow = win
		return win, s
	})

	return lim, stop
}

func main() {
	lim, _ := NewLimiter(time.Second, 10, func() (sw.Window, sw.StopFunc) {
		return sw.NewLocalWindow()
	})

	ok := lim.Allow()
	fmt.Printf("ok: %v\n", ok)
	fmt.Printf("curr-window-count: %v\n", lim.CurrWindow.Count())
}
```

Run the above code, then you will get the result as below:

```bash
$ go run main.go
ok: true
curr-window-count: 1
```

**Comment by giladlev23** [comment]
Nicely done!

Already been deployed in my system and works great.
Thanks a lot!

**Pull request closed without merging**
